CREATE TABLE `agenda_supplier` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`supplier_id` integer,
	`nama_supplier` text NOT NULL,
	`tipe` text DEFAULT 'kunjungan' NOT NULL,
	`tanggal` text NOT NULL,
	`jam` text,
	`lokasi` text,
	`petugas_id` integer,
	`hasil` text,
	`catatan` text,
	`status` text DEFAULT 'dijadwalkan' NOT NULL,
	`tenant_id` integer DEFAULT 1 NOT NULL,
	`created_by` integer,
	`updated_by` integer,
	`created_at` text DEFAULT (datetime('now','localtime')),
	`updated_at` text DEFAULT (datetime('now','localtime')),
	FOREIGN KEY (`supplier_id`) REFERENCES `supplier`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`petugas_id`) REFERENCES `karyawan`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `komplain_pelanggan` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`pelanggan_id` integer,
	`nama_pelanggan` text,
	`kategori` text DEFAULT 'lainnya' NOT NULL,
	`deskripsi` text NOT NULL,
	`tanggal` text NOT NULL,
	`status` text DEFAULT 'masuk' NOT NULL,
	`resolusi` text,
	`ditangani_oleh` integer,
	`tenant_id` integer DEFAULT 1 NOT NULL,
	`created_by` integer,
	`updated_by` integer,
	`created_at` text DEFAULT (datetime('now','localtime')),
	`updated_at` text DEFAULT (datetime('now','localtime')),
	FOREIGN KEY (`pelanggan_id`) REFERENCES `pelanggan`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`ditangani_oleh`) REFERENCES `karyawan`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `kunjungan_sales` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`pelanggan_id` integer,
	`nama_warung` text NOT NULL,
	`alamat` text,
	`petugas_id` integer,
	`tanggal` text NOT NULL,
	`tujuan` text DEFAULT 'prospek' NOT NULL,
	`hasil` text,
	`catatan` text,
	`status_tindak_lanjut` text DEFAULT 'open' NOT NULL,
	`tenant_id` integer DEFAULT 1 NOT NULL,
	`created_by` integer,
	`updated_by` integer,
	`created_at` text DEFAULT (datetime('now','localtime')),
	`updated_at` text DEFAULT (datetime('now','localtime')),
	FOREIGN KEY (`pelanggan_id`) REFERENCES `pelanggan`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`petugas_id`) REFERENCES `karyawan`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `permintaan_pelanggan` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`pelanggan_id` integer,
	`nama_pelanggan` text,
	`nama_barang` text NOT NULL,
	`barang_id` integer,
	`qty_minta` integer,
	`catatan` text,
	`status` text DEFAULT 'menunggu' NOT NULL,
	`tanggal` text NOT NULL,
	`ditangani_oleh` integer,
	`tenant_id` integer DEFAULT 1 NOT NULL,
	`created_by` integer,
	`updated_by` integer,
	`created_at` text DEFAULT (datetime('now','localtime')),
	`updated_at` text DEFAULT (datetime('now','localtime')),
	FOREIGN KEY (`pelanggan_id`) REFERENCES `pelanggan`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`barang_id`) REFERENCES `barang`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`ditangani_oleh`) REFERENCES `karyawan`(`id`) ON UPDATE no action ON DELETE no action
);
